version: "3.8"

services:
  redis-service:
    container_name: redis-container
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    restart: always

  redis-insight-service:
    container_name: redis-insight-container
    image: redislabs/redisinsight:latest
    ports:
      - ${REDIS_INSIGHT_PORT}:5540
    restart: always
